name: deploy
on:
  push:
    branches:
      - main
      - master
  
jobs:
  build-and-deploy:
    runs-on: scrbsmqdk007491
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1

          host: scrbsmqdk007491
          uses: ssh-action@master
          username: pkh045
          password: yc]%2z\93C(cB[WE
          port: 22
          script: |
            mkdir -p /home/pkh045/test
