name: deploy
on:
  push:
    branches:
      - main
      - master
  
jobs:
  build-and-deploy:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1


      - name: connect to server
        with:
          host: scrbsmqdk007491
          username: pkh045
          password: yc]%2z\93C(cB[WE
          port: 22
          script: |
            mkdir -p /home/pkh045/test
