name: run-script
on: push

jobs:
run:
runs-on: 
        - self-hosted
        - activemq_7491
steps:
- uses: actions/checkout@v1
- name: script
run: https://github.com/prachi-khirolkar/ActiveMQ_Test/create.sh
shell: bash
with:
