---
name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths-ignore:
      - ""
jobs:
  build: null
  runs-on:
      - self-hosted
      - activemq_7491
      - ubuntu-latest
  name: validation
  steps:
    - name: Checkout source code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: validation
      id: files
      run: |
        host: scrbsmqdk007491
        username: pkh045
        password: yc]%2z\93C(cB[WE
        port: 22
        script: |
          mkdir -p /home/pkh045/test
